#!/usr/bin/env bash
# adding a custom Nginx response header

sudo apt-get update
sudo apt-get -y install nginx
name="http {\n\tadd_header X-Served-By \"$HOSTNAME\";"
sudo sed -i "s/http {/$name/" /etc/nginx/nginx.conf
sudo service nginx restart
