#!/usr/bin/env bash
# installing and configuring HAproxy

sudo apt-get update
sudo apt-get install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.6
sudo apt-get install haproxy=2.6.\*

server_config=\
"
defaults
	mode http
	retries 3
	timeout connect 5s
	timeout client 10s
	timeout server 10s
	timeout http-request 10s

frontend tkamara-frontend
	bind *:80
	default_backend tkamara-backend

backend tkamara-backend
	balance roundrobin
	server 109158-web-01 54.237.12.161:80 check
	server 109158-web-02 54.236.54.57:80 check
"

echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

#enabling HAproxy to be started by init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart 
