#!/usr/bin/env bash
# using while loop to display a clock

hour=0

while [ "$hour" -lt 13 ]
do
	echo "Hour: $hour"

	minute=1

	while [ "$minute" -lt 60 ]
	do		
		echo "$minute"
		minute=$(( minute + 1 ))
	done
	hour=$(( hour + 1))
done
